language: python
matrix:
  include:
    - name: "Python 3.7 on Bionic"
      python: "3.7"
      dist: bionic
      addons:
        apt:
          packages:
            - flac


    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python flac
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script: pytest -s
